kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker-proxy.cloud.ga66a.ru/gradle:7.6.0-jdk17
  commands:
  - gradle assemble
  - set
  - printenv

trigger:
  event:
  - cron
  - custom
  - push
  - pull_request
  - tag
  - promote
  - rollback