kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker-proxy.cloud.ga66a.ru/gradle:7.6.0-jdk17
  commands:
  - gradle assemble
  - set
  - printenv

- name: docker-build
  image: docker-proxy.cloud.ga66a.ru/docker:dind
  volumes:
    - name: dockersock
      path: /var/run
    environment:
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_LOGIN:
        from_secret: DOCKER_LOGIN
  commands:
    - sleep 5 # give docker enough time to start
    - ls -la
    - set
    - docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD docker.cloud.ga66a.ru
    - docker image ls
    - docker build -t docker.cloud.ga66a.ru/iot-server:v0.0.1 .
    - docker image ls
#    - DOCKER_BUILDKIT=1 docker build -t example.org/image:latest . --target base
#    - docker image ls
#      - DOCKER_BUILDKIT=1 docker build -t example.org/image:tools . --target tools
#      - docker push --all-tags example.org/image

services:
  - name: docker
    image: docker-proxy.cloud.ga66a.ru/docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}


trigger:
  event:
  - cron
  - custom
  - push
  - pull_request
  - tag
  - promote
  - rollback