spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:localhost}:3306/iot-server?autoReconnect=true&useSSL=false
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
flyway:
  locations:
    - locations: classpath:db/migration/
logging:
  level:
    ROOT: INFO